# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Python version and requirements to build the docs
python:
  version: 3.7
  install:
    - requirements: requirements-docs.txt

# Build docs in all formats:
formats: all
