[tool.black] # https://black.readthedocs.io/en/stable/pyproject_toml.html
target-version = ['py37', 'py38']
include = '\.pyi?$' # Default
exclude = '''
# Directory exclusions
/(
  # Defaults:
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # Add additional patterns here:
  # | my_directory
)/

| # File exclusions
/(
  # Add additional file patterns here:
  # my_file\.py
)
'''

[tool.isort] # https://github.com/timothycrosley/isort/wiki/isort-Settings#full-reference-of-isort-settings
# Compatibility with Black (https://black.readthedocs.io/en/stable/the_black_code_style.html#how-black-wraps-lines)
# Style ---------------------
line_length=88
wrap_length=88
multi_line_output=3
combine_star='True'
combine_as_imports='True'
balanced_wrapping='True'
indent=4
lines_after_imports=2
lines_between_types=0
include_trailing_comma='True'
use_parentheses='True'
#force_single_line  #Would override mult-line_output
#force_grid_wrap    #Would override mult-line_output
# Sections ------------------
default_section="THIRDPARTY"
known_datascience=['pandas', 'numpy', 'scipy', 'sklearn']
import_heading_stdlib="Standard Library ---------------------------------------------------------------------"
import_heading_thirdparty="Third Party --------------------------------------------------------------------------"
import_heading_datascience="Data Science"
import_heading_firstparty="Project ------------------------------------------------------------------------------"
#forced_separate=""
# Order ---------------------
sections=['FUTURE','STDLIB', 'THIRDPARTY', 'DATASCIENCE', 'FIRSTPARTY','LOCALFOLDER']
case_sensitive='False'
length_sort='False'
order_by_type='True'
force_alphabetical_sort='False'
force_sort_within_sections='False'
from_first='False'
reverse-relative='True'
#force_to_top=""
# Inclusions/Exclusions -----
#skip               # Requires full file path
skip_glob=[
    ".eggs/**",
   ".git/*",
   ".hg/*",
   ".mypy_cache/*",
   ".tox/*",
   ".venv/*",
   "_build/*",
   "buck-out/*",
   "build/*",
   "dist/*",
  # Add additional patterns here:
  # "my_directory/*"
]
#not_skip=[]
#filter_files       # Does not seem to work...
# Other ---------------------
atomic='False'
